image: "ubuntu:latest"

build:cargo:
    before_script:
      - apt update -y && apt install -y llvm clang lld alsa curl libasound2-dev
      - curl https://sh.rustup.rs -sSf > rustup
      - sh rustup -y
      - source $HOME/.cargo/env
      - cargo install -f cargo-binutils
      - rustup default nightly
      - rustup component add llvm-tools-preview
    script:
        - cargo +nightly build --release

test:cargo:
    before_script:
      - apt update -y && apt install -y llvm clang lld alsa curl libasound2-dev
      - curl https://sh.rustup.rs -sSf > rustup
      - sh rustup -y
      - source $HOME/.cargo/env
      - cargo install -f cargo-binutils
      - rustup default nightly
      - rustup component add llvm-tools-preview
    script:
      - rustc --version && cargo --version  # Print version info for debugging
      - cargo +nightly test --workspace --verbose
