image: "rust:latest"

build:cargo:
    script:
        - cargo build --release

test:cargo:
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose
