[package]
name = "sepaeii_bevy"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.5.0", features = ["dynamic"] }
bevy_tiled_prototype = { git = "https://github.com/j-mcavoy/bevy_tiled.git" }
tiled = "0.9.5"
